name: Release

on:
  push:
    tags:
      - v[0-9]+.*
      - testing-ci.*

jobs:
  build-f31:
    name: Build Fedora 31 package
    runs-on: ubuntu-latest
    container: fedora:31
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        dnf distro-sync -y
        dnf install -y fedora-packager fedora-review
        dnf builddep -y .pkg/luks-keyfile-dracut.spec

    - name: Build package
      run: |
        cd .pkg/

        # Build the .rpm packages
        ./makerpm

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: fedora-31-latest
        path: .pkg/out/noarch

  release:
    name: Publish release
    needs: [build-f31]
    runs-on: ubuntu-latest
    steps:
    - name: Download Fedora 31 artifacts
      uses: actions/download-artifact@v1
      with:
        name: fedora-31-latest

    - name: Upload assets
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./*-latest/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
